name: trigger-merge-to-downstream

on:
  push:
    branches:
      - main
      - release/**

permissions:
  contents: read

jobs:
  trigger-merge:
    if: github.repository == 'hashicorp/boundary'
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    env:
      DOWNSTREAM_SLUG: ${{ vars.DOWNSTREAM_SLUG }}
      DOWNSTREAM_TOK: ${{ secrets.DOWNSTREAM_TOK }}
      DOWNSTREAM_WORKFLOW: ${{ vars.DOWNSTREAM_WORKFLOW }}
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - name: Trigger Merge
        run: |
          ./scripts/trigger-merge-to-downstream-gha ${{ github.ref_name }}
